### PR TITLE
add feature auto detect m_file_archive_start_ofs of zip

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Review by biodranik — APPROVED** [review]

**Comment by zhaozg** [comment]
rebased

**Review by MunifTanjim — APPROVED** [review]

**Comment by Bilal2453** [comment]
hey, @uroni can this be merged?

**Comment by Bilal2453** [comment]
to clarify, this is needed over in Luvi (the Luvit project) and would be nice if we can backport it here

**Comment by SinisterRectus** [comment]
Consider changing the 2-space indent to a 4-space indent for consistency.

**Pull request closed without merging**
